/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author kisan
 */
public class AddressInfoUI extends javax.swing.JPanel {
    
    AddressInfo addressInfo;

    /**
     * Creates new form AddressInfoUI
     * @param addressInfo
     */
    public AddressInfoUI(AddressInfo addressInfo) {
        initComponents();
        this.addressInfo = addressInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEnterAddress = new javax.swing.JLabel();
        lblStreetAddress = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblStateNumber = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtStreetAddress = new javax.swing.JTextField();
        txtCityName = new javax.swing.JTextField();
        txtStateName = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        jbSaveAddress = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblEnterAddress.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblEnterAddress.setText("Enter your Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 178, 0, 0);
        add(lblEnterAddress, gridBagConstraints);

        lblStreetAddress.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblStreetAddress.setText("    Enter street address :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 135, 0, 0);
        add(lblStreetAddress, gridBagConstraints);

        lblCityName.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblCityName.setText("          Enter city name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 130, 0, 0);
        add(lblCityName, gridBagConstraints);

        lblStateNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblStateNumber.setText("                        Enter the state name : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        add(lblStateNumber, gridBagConstraints);

        lblZipCode.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblZipCode.setText("                                     Enter zipcode :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 0);
        add(lblZipCode, gridBagConstraints);

        txtStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 346;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 10, 0, 153);
        add(txtStreetAddress, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 346;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 153);
        add(txtCityName, gridBagConstraints);

        txtStateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 346;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 153);
        add(txtStateName, gridBagConstraints);

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 346;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 10, 0, 153);
        add(txtZipCode, gridBagConstraints);

        jbSaveAddress.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jbSaveAddress.setText("SAVE");
        jbSaveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveAddressActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 10, 72, 0);
        add(jbSaveAddress, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressActionPerformed

    private void txtStateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateNameActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void jbSaveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveAddressActionPerformed
        addressInfo.setStreetAddress(txtStreetAddress.getText());
        addressInfo.setCity(txtCityName.getText());
        addressInfo.setState(txtStateName.getText());
        addressInfo.setZipCode(txtZipCode.getText());
        
        JOptionPane.showMessageDialog(this,"Address Information has been saved");
    }//GEN-LAST:event_jbSaveAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSaveAddress;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblEnterAddress;
    private javax.swing.JLabel lblStateNumber;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtStateName;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
