/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BankingCheckingInfo;
import Business.BankingInfo;
import Business.BankingSavingsInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author kisan
 */
public class BankingInfoUI extends javax.swing.JPanel {
    
    BankingInfo bankingInfo;
    BankingSavingsInfo bankingSavingsInfo;
    BankingCheckingInfo bankingCheckingInfo;

    /**
     * Creates new form BankingInfoUI
     * @param bankingInfo
     */
    public BankingInfoUI(BankingInfo bankingInfo, BankingSavingsInfo bankingSavingsInfo, BankingCheckingInfo bankingCheckingInfo) {
        initComponents();
        this.bankingInfo = bankingInfo;
        this.bankingSavingsInfo = bankingSavingsInfo;
        this.bankingCheckingInfo = bankingCheckingInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEnterBankInfo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutingNumber = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtBankRoutingNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtAccountBalance = new javax.swing.JTextField();
        jbSaveBank = new javax.swing.JButton();
        txtAccountBalance1 = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        lblAccountBalance1 = new javax.swing.JLabel();
        txtBankAccountNumber1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblEnterBankInfo.setBackground(new java.awt.Color(255, 191, 0));
        lblEnterBankInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblEnterBankInfo.setText("Enter your Bank Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 122, 0, 87);
        add(lblEnterBankInfo, gridBagConstraints);

        lblBankName.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBankName.setText("  Enter the bank name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 130, 0, 0);
        add(lblBankName, gridBagConstraints);

        lblBankRoutingNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBankRoutingNumber.setText("  Enter your bank routing number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 42, 0, 0);
        add(lblBankRoutingNumber, gridBagConstraints);

        lblPhoneNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPhoneNumber.setText("      Enter your bank account number : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 17, 0, 0);
        add(lblPhoneNumber, gridBagConstraints);

        lblAccountBalance.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAccountBalance.setText("                  Enter your account balance : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(lblAccountBalance, gridBagConstraints);

        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 7, 0, 0);
        add(txtBankName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 7, 0, 0);
        add(txtBankRoutingNumber, gridBagConstraints);

        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 7, 0, 0);
        add(txtBankAccountNumber, gridBagConstraints);

        txtAccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountBalanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 7, 0, 0);
        add(txtAccountBalance, gridBagConstraints);

        jbSaveBank.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jbSaveBank.setText("SAVE");
        jbSaveBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveBankActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(101, 98, 42, 0);
        add(jbSaveBank, gridBagConstraints);

        txtAccountBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountBalance1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 7, 0, 0);
        add(txtAccountBalance1, gridBagConstraints);

        lblPhoneNumber1.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPhoneNumber1.setText("      Enter your bank account number : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 17, 0, 0);
        add(lblPhoneNumber1, gridBagConstraints);

        lblAccountBalance1.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAccountBalance1.setText("                  Enter your account balance : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(lblAccountBalance1, gridBagConstraints);

        txtBankAccountNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumber1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 7, 0, 0);
        add(txtBankAccountNumber1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel1.setText("-- CHECKING ACCOUNT INFO --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 47, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 20)); // NOI18N
        jLabel2.setText("-- SAVINGS ACCOUNT INFO --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 52, 0, 0);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtAccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountBalanceActionPerformed

    private void jbSaveBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveBankActionPerformed
        bankingInfo.setBankName(txtBankName.getText());
        bankingInfo.setBankRoutingNumber(txtBankRoutingNumber.getText());
        bankingSavingsInfo.setSavingsAccountNumber(txtBankAccountNumber.getText());
        bankingSavingsInfo.setSavingsBalance(txtAccountBalance.getText());
        bankingCheckingInfo.setCheckingAccountNumber(txtBankAccountNumber1.getText());
        bankingCheckingInfo.setCheckingBalance(txtAccountBalance1.getText());
        
        JOptionPane.showMessageDialog(this,"Banking Information has been saved");    
    }//GEN-LAST:event_jbSaveBankActionPerformed

    private void txtAccountBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountBalance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountBalance1ActionPerformed

    private void txtBankAccountNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumber1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbSaveBank;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountBalance1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblEnterBankInfo;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JTextField txtAccountBalance;
    private javax.swing.JTextField txtAccountBalance1;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBankAccountNumber1;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBankRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
