/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DriverInfo;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author kisan
 */
public class DriverInfoUI extends javax.swing.JPanel {
    
    DriverInfo driverInfo;

    /**
     * Creates new form DriverInfoUI
     * @param driverInfo
     */
    public DriverInfoUI(DriverInfo driverInfo) {
        initComponents();
        this.driverInfo = driverInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEnterDriverInfo = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblLicenseDOI = new javax.swing.JLabel();
        lblLicenseDOE = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtLicenseDOI = new javax.swing.JTextField();
        txtLicenseDOE = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        jbSaveDriver = new javax.swing.JButton();
        jbUploda = new javax.swing.JButton();
        txtPicture = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblEnterDriverInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblEnterDriverInfo.setText("Enter your Driving Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(155, 225, 0, 0);
        add(lblEnterDriverInfo, gridBagConstraints);

        lblLicenseNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseNumber.setText("  Enter the license number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 269, 0, 0);
        add(lblLicenseNumber, gridBagConstraints);

        lblLicenseDOI.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseDOI.setText("    Enter your license date of issue :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 214, 0, 0);
        add(lblLicenseDOI, gridBagConstraints);

        lblLicenseDOE.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseDOE.setText("     Enter your license expiration date : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 192, 0, 0);
        add(lblLicenseDOE, gridBagConstraints);

        lblBloodType.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBloodType.setText("                       Enter your blood type : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 192, 0, 0);
        add(lblBloodType, gridBagConstraints);

        lblPicture.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPicture.setText("              Enter your picture : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 255, 0, 0);
        add(lblPicture, gridBagConstraints);

        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        add(txtLicenseNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        add(txtLicenseDOI, gridBagConstraints);

        txtLicenseDOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseDOEActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        add(txtLicenseDOE, gridBagConstraints);

        txtBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 0);
        add(txtBloodType, gridBagConstraints);

        jbSaveDriver.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jbSaveDriver.setText("SAVE");
        jbSaveDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveDriverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 18, 249, 0);
        add(jbSaveDriver, gridBagConstraints);

        jbUploda.setText("Upload an Image");
        jbUploda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUplodaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 31, 0, 179);
        add(jbUploda, gridBagConstraints);

        txtPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPictureActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 0, 0);
        add(txtPicture, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtLicenseDOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseDOEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseDOEActionPerformed

    private void txtBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodTypeActionPerformed

    private void jbSaveDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveDriverActionPerformed
        driverInfo.setLicenseNumber(txtLicenseNumber.getText());
        driverInfo.setDateOfIssue(txtLicenseDOI.getText());
        driverInfo.setDateOfExpiration(txtLicenseDOE.getText());
        driverInfo.setBloodType(txtBloodType.getText());
        driverInfo.setPicture(txtPicture.getText());
        
        JOptionPane.showMessageDialog(this,"Driver's Information has been saved");
    }//GEN-LAST:event_jbSaveDriverActionPerformed

    private void jbUplodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUplodaActionPerformed
         JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new java.io.File("C:/Users"));
            fc.setDialogTitle("File Browser.");
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            if (fc.showOpenDialog(jbUploda) == JFileChooser.APPROVE_OPTION){
                txtPicture.setText(fc.getSelectedFile().getAbsolutePath());
            }
    }//GEN-LAST:event_jbUplodaActionPerformed

    private void txtPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPictureActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSaveDriver;
    private javax.swing.JButton jbUploda;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblEnterDriverInfo;
    private javax.swing.JLabel lblLicenseDOE;
    private javax.swing.JLabel lblLicenseDOI;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtLicenseDOE;
    private javax.swing.JTextField txtLicenseDOI;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtPicture;
    // End of variables declaration//GEN-END:variables
}
