/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.MedicalInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author kisan
 */
public class MedicalInfoUI extends javax.swing.JPanel {
    
    MedicalInfo medicalInfo; 

    /**
     * Creates new form MedicalInfoUI
     * @param medicalInfo
     */
    public MedicalInfoUI(MedicalInfo medicalInfo) {
        initComponents();
        this.medicalInfo = medicalInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblMedicalInfo = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAllergyOne = new javax.swing.JLabel();
        lblAllergyTwo = new javax.swing.JLabel();
        lblAllergyThree = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtAllergyOne = new javax.swing.JTextField();
        txtAllergyTwo = new javax.swing.JTextField();
        txtAllergyThree = new javax.swing.JTextField();
        jbSaveMedical = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblMedicalInfo.setBackground(new java.awt.Color(255, 191, 0));
        lblMedicalInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblMedicalInfo.setText("Enter your Medical Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 65, 0, 111);
        add(lblMedicalInfo, gridBagConstraints);

        lblMedicalRecordNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblMedicalRecordNumber.setText(" Enter the medical record number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 65, 0, 0);
        add(lblMedicalRecordNumber, gridBagConstraints);

        lblAllergyOne.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyOne.setText("                           Enter Allergy 1 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 0);
        add(lblAllergyOne, gridBagConstraints);

        lblAllergyTwo.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyTwo.setText("                                Enter Allergy 2 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        add(lblAllergyTwo, gridBagConstraints);

        lblAllergyThree.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyThree.setText("                                   Enter Allergy 3 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 0);
        add(lblAllergyThree, gridBagConstraints);

        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 0, 0);
        add(txtMedicalRecordNumber, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        add(txtAllergyOne, gridBagConstraints);

        txtAllergyTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        add(txtAllergyTwo, gridBagConstraints);

        txtAllergyThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(txtAllergyThree, gridBagConstraints);

        jbSaveMedical.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jbSaveMedical.setText("SAVE");
        jbSaveMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveMedicalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 18, 115, 0);
        add(jbSaveMedical, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtAllergyTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergyTwoActionPerformed

    private void txtAllergyThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergyThreeActionPerformed

    private void jbSaveMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveMedicalActionPerformed
        
        medicalInfo.setMedicalRecordNumber(txtMedicalRecordNumber.getText());
        medicalInfo.setAlergy_one(txtAllergyOne.getText());
        medicalInfo.setAlergy_two(txtAllergyTwo.getText());
        medicalInfo.setAlergy_three(txtAllergyThree.getText());
        
        JOptionPane.showMessageDialog(this,"Medical Information has been saved");
    }//GEN-LAST:event_jbSaveMedicalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSaveMedical;
    private javax.swing.JLabel lblAllergyOne;
    private javax.swing.JLabel lblAllergyThree;
    private javax.swing.JLabel lblAllergyTwo;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JTextField txtAllergyOne;
    private javax.swing.JTextField txtAllergyThree;
    private javax.swing.JTextField txtAllergyTwo;
    private javax.swing.JTextField txtMedicalRecordNumber;
    // End of variables declaration//GEN-END:variables
}
