/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;
import Business.BankingCheckingInfo;
import Business.BankingInfo;
import Business.BankingSavingsInfo;
import Business.DemoInfo;
import Business.DriverInfo;
import Business.MedicalInfo;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author kisan
 */
public class ReportUI extends javax.swing.JPanel {
    
    DemoInfo demoInfo;
    AddressInfo addressInfo;
    BankingInfo bankingInfo;
    DriverInfo driverInfo;
    MedicalInfo medicalInfo;
    BankingCheckingInfo bankingCheckingInfo;
    BankingSavingsInfo bankingSavings;

    /**
     * Creates new form ReportUI
     * @param demoInfo
     * @param addressInfo
     * @param bankingInfo
     * @param driverInfo
     * @param medicalInfo
     * @param bankingSavings
     * @param bankingCheckingInfo
     * @throws java.io.IOException
     */
    public ReportUI(DemoInfo demoInfo,AddressInfo addressInfo,BankingInfo bankingInfo,DriverInfo driverInfo,MedicalInfo medicalInfo,BankingSavingsInfo bankingSavings,BankingCheckingInfo bankingCheckingInfo) throws IOException {
        initComponents();
        this.demoInfo = demoInfo;
        this.addressInfo = addressInfo;
        this.bankingInfo = bankingInfo;
        this.driverInfo = driverInfo;
        this.medicalInfo = medicalInfo;
        this.bankingSavings = bankingSavings;
        this.bankingCheckingInfo = bankingCheckingInfo;
        displayProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtstreet = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtmcr = new javax.swing.JTextField();
        txta1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txta2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txta3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblpicture = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtlnumber = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtldoi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtldoe = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtblood = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtroutingnumber = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtsavingacc = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtsavingbal = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtcheckingacc = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtcheckingbal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel2.setText("Last Name :");

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number :");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel5.setText("Date of Birth :");

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel6.setText("Fisrt Name :");

        txtfname.setEditable(false);
        txtfname.setBackground(new java.awt.Color(255, 255, 255));
        txtfname.setToolTipText("");
        txtfname.setBorder(null);

        txtlname.setEditable(false);
        txtlname.setBackground(new java.awt.Color(255, 255, 255));
        txtlname.setToolTipText("");
        txtlname.setBorder(null);

        txtphoneno.setEditable(false);
        txtphoneno.setBackground(new java.awt.Color(255, 255, 255));
        txtphoneno.setToolTipText("");
        txtphoneno.setBorder(null);

        txtdob.setEditable(false);
        txtdob.setBackground(new java.awt.Color(255, 255, 255));
        txtdob.setToolTipText("");
        txtdob.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel7.setText("Age :");

        txtage.setEditable(false);
        txtage.setBackground(new java.awt.Color(255, 255, 255));
        txtage.setToolTipText("");
        txtage.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel8.setText("Height :");

        txtheight.setEditable(false);
        txtheight.setBackground(new java.awt.Color(255, 255, 255));
        txtheight.setToolTipText("");
        txtheight.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel9.setText("Weight :");

        txtweight.setEditable(false);
        txtweight.setBackground(new java.awt.Color(255, 255, 255));
        txtweight.setToolTipText("");
        txtweight.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel10.setText("SSN :");

        txtssn.setEditable(false);
        txtssn.setBackground(new java.awt.Color(255, 255, 255));
        txtssn.setToolTipText("");
        txtssn.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel11.setText("Street :");

        txtstreet.setEditable(false);
        txtstreet.setBackground(new java.awt.Color(255, 255, 255));
        txtstreet.setBorder(null);
        txtstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstreetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel12.setText("City :");

        txtcity.setEditable(false);
        txtcity.setBackground(new java.awt.Color(255, 255, 255));
        txtcity.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel13.setText("State :");

        txtstate.setEditable(false);
        txtstate.setBackground(new java.awt.Color(255, 255, 255));
        txtstate.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel14.setText("ZipCode :");

        txtzipcode.setEditable(false);
        txtzipcode.setBackground(new java.awt.Color(255, 255, 255));
        txtzipcode.setBorder(null);

        jLabel15.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel15.setText("Medical R-Number :");

        txtmcr.setEditable(false);
        txtmcr.setBackground(new java.awt.Color(255, 255, 255));
        txtmcr.setBorder(null);

        txta1.setEditable(false);
        txta1.setBackground(new java.awt.Color(255, 255, 255));
        txta1.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel16.setText("Allergy 2 :");

        txta2.setEditable(false);
        txta2.setBackground(new java.awt.Color(255, 255, 255));
        txta2.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel17.setText("Allergy 3 :");

        txta3.setEditable(false);
        txta3.setBackground(new java.awt.Color(255, 255, 255));
        txta3.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel18.setText("Allergy 1 :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txta3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txta2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txta1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtmcr))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtzipcode))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtstate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtcity))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtstreet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtssn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtweight))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtheight))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdob))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtphoneno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtlname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtdob))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtage))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtheight))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtweight))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtssn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtstreet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtcity))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtstate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtzipcode))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtmcr))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txta1)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txta2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txta3))
                .addGap(25, 25, 25))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblpicture.setBackground(new java.awt.Color(255, 255, 255));
        lblpicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel19.setText("License Number :");

        txtlnumber.setEditable(false);
        txtlnumber.setBackground(new java.awt.Color(255, 255, 255));
        txtlnumber.setBorder(null);

        jLabel20.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel20.setText("License DOI :");

        txtldoi.setEditable(false);
        txtldoi.setBackground(new java.awt.Color(255, 255, 255));
        txtldoi.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel21.setText("License DOE :");

        txtldoe.setEditable(false);
        txtldoe.setBackground(new java.awt.Color(255, 255, 255));
        txtldoe.setBorder(null);

        jLabel22.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel22.setText("Blood Type :");

        txtblood.setEditable(false);
        txtblood.setBackground(new java.awt.Color(255, 255, 255));
        txtblood.setBorder(null);

        jLabel23.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel23.setText("Bank Name :");

        txtbankname.setEditable(false);
        txtbankname.setBackground(new java.awt.Color(255, 255, 255));
        txtbankname.setBorder(null);

        jLabel24.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel24.setText("Bank Route Number :");

        txtroutingnumber.setEditable(false);
        txtroutingnumber.setBackground(new java.awt.Color(255, 255, 255));
        txtroutingnumber.setBorder(null);

        jLabel25.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel25.setText("Saving Account No :");

        txtsavingacc.setEditable(false);
        txtsavingacc.setBackground(new java.awt.Color(255, 255, 255));
        txtsavingacc.setBorder(null);

        jLabel26.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel26.setText("Saving Acc Balance :");

        txtsavingbal.setEditable(false);
        txtsavingbal.setBackground(new java.awt.Color(255, 255, 255));
        txtsavingbal.setBorder(null);

        jLabel27.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel27.setText("Checking Acc No :");

        txtcheckingacc.setEditable(false);
        txtcheckingacc.setBackground(new java.awt.Color(255, 255, 255));
        txtcheckingacc.setBorder(null);
        txtcheckingacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckingaccActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel28.setText("Checking Acc Balance :");

        txtcheckingbal.setEditable(false);
        txtcheckingbal.setBackground(new java.awt.Color(255, 255, 255));
        txtcheckingbal.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setText("Profile Picture :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addGap(7, 7, 7)
                            .addComponent(txtcheckingbal))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtcheckingacc))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtsavingbal))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtsavingacc))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtblood))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtlnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtldoi))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtldoe))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtbankname)
                                .addComponent(txtroutingnumber))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtlnumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtldoi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtldoe)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtblood, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtbankname))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtroutingnumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtsavingacc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtsavingbal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtcheckingacc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtcheckingbal))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblpicture, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstreetActionPerformed

    private void txtcheckingaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckingaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckingaccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JTextField txta1;
    private javax.swing.JTextField txta2;
    private javax.swing.JTextField txta3;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtblood;
    private javax.swing.JTextField txtcheckingacc;
    private javax.swing.JTextField txtcheckingbal;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtldoe;
    private javax.swing.JTextField txtldoi;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtlnumber;
    private javax.swing.JTextField txtmcr;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtroutingnumber;
    private javax.swing.JTextField txtsavingacc;
    private javax.swing.JTextField txtsavingbal;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreet;
    private javax.swing.JTextField txtweight;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
private void displayProducts() throws IOException {
    ImageIcon imageIconOne = new ImageIcon(driverInfo.getPicture());
    Image image = imageIconOne.getImage();
    Image newimg = image.getScaledInstance(618, 276, java.awt.Image.SCALE_SMOOTH);  
    imageIconOne = new ImageIcon(newimg);
    
    txtfname.setText(demoInfo.getFirstName());
    txtlname.setText(demoInfo.getLastName());
    txtphoneno.setText(demoInfo.getPhoneNumber());
    txtdob.setText(demoInfo.getDOB());
    txtage.setText(demoInfo.getAge());
    txtheight.setText(demoInfo.getHeight());
    txtweight.setText(demoInfo.getWeight());
    txtssn.setText(demoInfo.getSSN());
    txtstreet.setText(addressInfo.getStreetAddress());
    txtcity.setText(addressInfo.getCity());
    txtstate.setText(addressInfo.getState());
    txtzipcode.setText(addressInfo.getZipCode());
    txtbankname.setText(bankingInfo.getBankName());
    txta3.setText(medicalInfo.getAlergy_three());
    txta2.setText(medicalInfo.getAlergy_two());
    txta1.setText(medicalInfo.getAlergy_one());
    txtmcr.setText(medicalInfo.getMedicalRecordNumber());
    lblpicture.setIcon(imageIconOne);
    txtblood.setText(driverInfo.getBloodType());
    txtldoe.setText(driverInfo.getDateOfExpiration());
    txtldoi.setText(driverInfo.getDateOfIssue());
    txtlnumber.setText(driverInfo.getLicenseNumber());
    txtcheckingacc.setText(bankingCheckingInfo.getCheckingAccountNumber());
    txtsavingbal.setText(bankingSavings.getSavingsBalance());
    txtsavingacc.setText(bankingSavings.getSavingsAccountNumber());
    txtroutingnumber.setText(bankingInfo.getBankRoutingNumber());  
    txtcheckingbal.setText(bankingCheckingInfo.getCheckingBalance());
}

}

