/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.MedicalInfo;

/**
 *
 * @author kisan
 */
public class ViewMedicalInfo extends javax.swing.JPanel {
    
    MedicalInfo medicalInfo;

    /**
     * Creates new form ViewMedicalInfo
     */
    public ViewMedicalInfo(MedicalInfo medicalInfo) {
        initComponents();
        this.medicalInfo = medicalInfo;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblMedicalInfo = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAllergyOne = new javax.swing.JLabel();
        lblAllergyTwo = new javax.swing.JLabel();
        lblAllergyThree = new javax.swing.JLabel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtAllergyOne = new javax.swing.JTextField();
        txtAllergyTwo = new javax.swing.JTextField();
        txtAllergyThree = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblMedicalInfo.setBackground(new java.awt.Color(255, 191, 0));
        lblMedicalInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblMedicalInfo.setText("       Medical Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 149;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(128, 137, 0, 108);
        add(lblMedicalInfo, gridBagConstraints);

        lblMedicalRecordNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblMedicalRecordNumber.setText("              Medical record number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 137, 0, 0);
        add(lblMedicalRecordNumber, gridBagConstraints);

        lblAllergyOne.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyOne.setText("                                   Allergy 1 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 137, 0, 0);
        add(lblAllergyOne, gridBagConstraints);

        lblAllergyTwo.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyTwo.setText("                                        Allergy 2 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 112, 0, 0);
        add(lblAllergyTwo, gridBagConstraints);

        lblAllergyThree.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAllergyThree.setText("                                           Allergy 3 :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 95, 286, 0);
        add(lblAllergyThree, gridBagConstraints);

        txtMedicalRecordNumber.setEditable(false);
        txtMedicalRecordNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtMedicalRecordNumber.setBorder(null);
        txtMedicalRecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalRecordNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 0, 0);
        add(txtMedicalRecordNumber, gridBagConstraints);

        txtAllergyOne.setEditable(false);
        txtAllergyOne.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergyOne.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 0);
        add(txtAllergyOne, gridBagConstraints);

        txtAllergyTwo.setEditable(false);
        txtAllergyTwo.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergyTwo.setBorder(null);
        txtAllergyTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyTwoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        add(txtAllergyTwo, gridBagConstraints);

        txtAllergyThree.setEditable(false);
        txtAllergyThree.setBackground(new java.awt.Color(255, 255, 255));
        txtAllergyThree.setBorder(null);
        txtAllergyThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergyThreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        add(txtAllergyThree, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalRecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalRecordNumberActionPerformed

    private void txtAllergyTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergyTwoActionPerformed

    private void txtAllergyThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergyThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergyThreeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAllergyOne;
    private javax.swing.JLabel lblAllergyThree;
    private javax.swing.JLabel lblAllergyTwo;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JTextField txtAllergyOne;
    private javax.swing.JTextField txtAllergyThree;
    private javax.swing.JTextField txtAllergyTwo;
    private javax.swing.JTextField txtMedicalRecordNumber;
    // End of variables declaration//GEN-END:variables

    private void display() {
        txtMedicalRecordNumber.setText(medicalInfo.getMedicalRecordNumber());
        txtAllergyOne.setText(medicalInfo.getAlergy_one());
        txtAllergyTwo.setText(medicalInfo.getAlergy_two());
        txtAllergyThree.setText(medicalInfo.getAlergy_three());
    }
}
