/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BankingCheckingInfo;
import Business.BankingInfo;
import Business.BankingSavingsInfo;

/**
 *
 * @author kisan
 */
public class ViewBankingInfo extends javax.swing.JPanel {
    
    BankingInfo bankingInfo;
    BankingCheckingInfo bankCheckingInfo;
    BankingSavingsInfo bankSavingsInfo;
    
    /**
     * Creates new form ViewBankingInfo
     * @param bankingInfo
     * @param bankSavingsInfo
     * @param bankCheckingInfo
     */
    public ViewBankingInfo(BankingInfo bankingInfo,BankingSavingsInfo bankSavingsInfo,BankingCheckingInfo bankCheckingInfo) {
        initComponents();
        this.bankingInfo = bankingInfo;
        this.bankSavingsInfo = bankSavingsInfo;
        this.bankCheckingInfo = bankCheckingInfo;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEnterBankInfo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutingNumber = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtBankRoutingNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtAccountBalance = new javax.swing.JTextField();
        txtBankAccountNumber1 = new javax.swing.JTextField();
        txtAccountBalance1 = new javax.swing.JTextField();
        lblPhoneNumber1 = new javax.swing.JLabel();
        lblAccountBalance1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblEnterBankInfo.setBackground(new java.awt.Color(255, 191, 0));
        lblEnterBankInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblEnterBankInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterBankInfo.setText("        Bank Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(87, 187, 0, 0);
        add(lblEnterBankInfo, gridBagConstraints);

        lblBankName.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBankName.setText("                Bank name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 165, 0, 0);
        add(lblBankName, gridBagConstraints);

        lblBankRoutingNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBankRoutingNumber.setText("                  Bank routing number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 0, 0);
        add(lblBankRoutingNumber, gridBagConstraints);

        lblPhoneNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPhoneNumber.setText("                      Bank account number : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 52, 0, 0);
        add(lblPhoneNumber, gridBagConstraints);

        lblAccountBalance.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAccountBalance.setText("                                  Account balance : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 35, 0, 0);
        add(lblAccountBalance, gridBagConstraints);

        txtBankName.setEditable(false);
        txtBankName.setBackground(new java.awt.Color(255, 255, 255));
        txtBankName.setBorder(null);
        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 8, 0, 375);
        add(txtBankName, gridBagConstraints);

        txtBankRoutingNumber.setEditable(false);
        txtBankRoutingNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtBankRoutingNumber.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 8, 0, 375);
        add(txtBankRoutingNumber, gridBagConstraints);

        txtBankAccountNumber.setEditable(false);
        txtBankAccountNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtBankAccountNumber.setBorder(null);
        txtBankAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 8, 0, 375);
        add(txtBankAccountNumber, gridBagConstraints);

        txtAccountBalance.setEditable(false);
        txtAccountBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBalance.setBorder(null);
        txtAccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountBalanceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 8, 0, 375);
        add(txtAccountBalance, gridBagConstraints);

        txtBankAccountNumber1.setEditable(false);
        txtBankAccountNumber1.setBackground(new java.awt.Color(255, 255, 255));
        txtBankAccountNumber1.setBorder(null);
        txtBankAccountNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccountNumber1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 8, 0, 375);
        add(txtBankAccountNumber1, gridBagConstraints);

        txtAccountBalance1.setEditable(false);
        txtAccountBalance1.setBackground(new java.awt.Color(255, 255, 255));
        txtAccountBalance1.setBorder(null);
        txtAccountBalance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountBalance1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 8, 0, 375);
        add(txtAccountBalance1, gridBagConstraints);

        lblPhoneNumber1.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPhoneNumber1.setText("                      Bank account number : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 52, 0, 0);
        add(lblPhoneNumber1, gridBagConstraints);

        lblAccountBalance1.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblAccountBalance1.setText("                                  Account balance : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 35, 217, 0);
        add(lblAccountBalance1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel1.setText(" -- Checking Account Info --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 25, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 1, 24)); // NOI18N
        jLabel2.setText(" -- Savings Account Info --");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 46, 0, 0);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtBankAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumberActionPerformed

    private void txtAccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountBalanceActionPerformed

    private void txtBankAccountNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccountNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccountNumber1ActionPerformed

    private void txtAccountBalance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountBalance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountBalance1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountBalance1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutingNumber;
    private javax.swing.JLabel lblEnterBankInfo;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JTextField txtAccountBalance;
    private javax.swing.JTextField txtAccountBalance1;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBankAccountNumber1;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBankRoutingNumber;
    // End of variables declaration//GEN-END:variables

    private void display() {
        txtBankName.setText(bankingInfo.getBankName());
        txtBankRoutingNumber.setText(bankingInfo.getBankRoutingNumber());
        txtBankAccountNumber.setText(bankSavingsInfo.getSavingsAccountNumber());
        txtAccountBalance.setText(bankSavingsInfo.getSavingsBalance());
        txtBankAccountNumber1.setText(bankCheckingInfo.getCheckingAccountNumber());
        txtAccountBalance1.setText(bankCheckingInfo.getCheckingBalance());
    }
}
