/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DriverInfo;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author kisan
 */
public class ViewDriverInfo extends javax.swing.JPanel {
    
    DriverInfo driverInfo ;

    /**
     * Creates new form ViewDriverInfo
     * @param driverInfo
     */
    public ViewDriverInfo(DriverInfo driverInfo) {
        initComponents();
        this.driverInfo = driverInfo;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEnterDriverInfo = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lblLicenseDOI = new javax.swing.JLabel();
        lblLicenseDOE = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        txtLicenseDOI = new javax.swing.JTextField();
        txtLicenseDOE = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        lblEnterDriverInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 48)); // NOI18N
        lblEnterDriverInfo.setText("Driving Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(128, 163, 0, 0);
        add(lblEnterDriverInfo, gridBagConstraints);

        lblLicenseNumber.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseNumber.setText("                License number :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 101, 0, 0);
        add(lblLicenseNumber, gridBagConstraints);

        lblLicenseDOI.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseDOI.setText("                    License date of issue :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 46, 0, 0);
        add(lblLicenseDOI, gridBagConstraints);

        lblLicenseDOE.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblLicenseDOE.setText("                     License expiration date : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        add(lblLicenseDOE, gridBagConstraints);

        lblBloodType.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblBloodType.setText("                                       Blood type : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 24, 0, 0);
        add(lblBloodType, gridBagConstraints);

        lblPicture.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        lblPicture.setText("                               Picture : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 87, 0, 0);
        add(lblPicture, gridBagConstraints);

        txtLicenseNumber.setEditable(false);
        txtLicenseNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtLicenseNumber.setBorder(null);
        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 80);
        add(txtLicenseNumber, gridBagConstraints);

        txtLicenseDOI.setEditable(false);
        txtLicenseDOI.setBackground(new java.awt.Color(255, 255, 255));
        txtLicenseDOI.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 18, 0, 80);
        add(txtLicenseDOI, gridBagConstraints);

        txtLicenseDOE.setEditable(false);
        txtLicenseDOE.setBackground(new java.awt.Color(255, 255, 255));
        txtLicenseDOE.setBorder(null);
        txtLicenseDOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseDOEActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 80);
        add(txtLicenseDOE, gridBagConstraints);

        txtBloodType.setEditable(false);
        txtBloodType.setBackground(new java.awt.Color(255, 255, 255));
        txtBloodType.setBorder(null);
        txtBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 80);
        add(txtBloodType, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 345;
        gridBagConstraints.ipady = 175;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 22, 80);
        add(lblImage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed

    private void txtLicenseDOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseDOEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseDOEActionPerformed

    private void txtBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblEnterDriverInfo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicenseDOE;
    private javax.swing.JLabel lblLicenseDOI;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtLicenseDOE;
    private javax.swing.JTextField txtLicenseDOI;
    private javax.swing.JTextField txtLicenseNumber;
    // End of variables declaration//GEN-END:variables

    private void display() {
        ImageIcon imageIconOne = new ImageIcon(driverInfo.getPicture());
        Image image = imageIconOne.getImage();
        Image newimg = image.getScaledInstance(345, 175,  java.awt.Image.SCALE_SMOOTH);  
        imageIconOne = new ImageIcon(newimg);
        txtBloodType.setText(driverInfo.getBloodType());
        txtLicenseDOE.setText(driverInfo.getDateOfExpiration());
        txtLicenseDOI.setText(driverInfo.getDateOfIssue());
        txtLicenseNumber.setText(driverInfo.getLicenseNumber());
        lblImage.setIcon(imageIconOne);
    }
}
